FROM python:3.8-bullseye
ENV IS_DOCKER True

# add wait-for-it
COPY /docker/wait-for-it.sh /wait-for-it.sh
RUN chmod +x wait-for-it.sh

COPY ./kafka-feed /kafka-feed/
WORKDIR /kafka-feed

RUN pip3 install -r ./requirements.txt
RUN chmod +x ./scripts/cryptofeed_0_startup.sh
CMD ["/wait-for-it.sh", "redpanda:29092", "--", "/kafka-feed/scripts/cryptofeed_0_startup.sh"]
